#!/usr/bin/env bash
# A script to change localhost addresses

cp /etc/hosts /etc/hosts.bak
sed -i 's/^127\.0\.0\.1.*localhost/127.0.0.2 localhost/' /etc/hosts
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8    facebook.com" >> /etc/hosts