#!/usr/bin/env bash
# A script to change localhost addresses

sudo cp /etc/hosts /etc/hosts.bak
sudo sh -c 'echo "127.0.0.2    localhost" > /etc/hosts'
sudo sh -c 'echo "8.8.8.8    facebook.com" >> /etc/hosts'