#!/usr/bin/env bash
# A script to change localhost addresses

cp /etc/hosts /etc/hosts.bak
awk '{ if ($2 == "localhost") print "127.0.0.2 localhost"; else print $0 }' /etc/hosts > /tmp/hosts.new
grep -q "facebook.com" /tmp/hosts.new || echo "8.8.8.8    facebook.com" >> /tmp/hosts.new
mv /tmp/hosts.new /etc/hosts